version: '3.3'

services:
  # wildfly:
  #   image: wildfly-inova-cnj
  #   environment:
  #     NODE_HOSTNAME: wildfly
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #     - "8787:8787"
  #     - "9990:9990"
  #     - "9999:9999"
  #   volumes:
  #     - ~/projects/docker/inova-cnj/wildfly/standalone/data:/opt/wildfly/standalone/data
  #     - ~/projects/docker/inova-cnj/wildfly/standalone/log:/opt/wildfly/standalone/log
  #     - ~/projects/docker/inova-cnj/wildfly/standalone/deployments:/opt/wildfly/standalone/deployments
  #   networks:
  #     - inova-cnj-network

  ia-core:
    image: ia-core    
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - inova-cnj-network

networks: 
  inova-cnj-network:
    driver: overlay